---
- name: ProjectConfig event
  debug:
    msg: "New project event"

- name: Find all projects
  # Review Ansible version and use k8s_facts if is below 2.7
  k8s_info:
    api_version: project.openshift.io/v1
    kind: Project
  register:
    project_list

- name: Create Secret in all projects for Users
  include_tasks: "{{role_path}}/tasks/secret_tasks.yml"
  loop: "{{ project_list.resources }}"
  loop_control:
    loop_var: project
