- name: Get Secret
  k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{project.metadata.name}}"
    name: "{{secretname}}"
  register:
    secrets

- name: Create Secret if not exists
  when:
    - secrets.resources | length < 1
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/secret_template.yaml.j2') }}"