apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-config-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: project-config-operator
  template:
    metadata:
      labels:
        name: project-config-operator
    spec:
      serviceAccountName: project-config-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "project-config-operator:v1.0.0"
          imagePullPolicy: "Never"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "project-config-operator:v1.0.0"
          imagePullPolicy: "Never"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "project-config-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
